# Generated by Django 5.1.1 on 2024-10-30 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'document_titles',
            },
        ),
        migrations.CreateModel(
            name='EquipmentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
            ],
            options={
                'db_table': 'equipment_group',
            },
        ),
        migrations.CreateModel(
            name='RoleNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=90)),
            ],
            options={
                'db_table': 'role_names',
            },
        ),
        migrations.CreateModel(
            name='DocumentClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded', models.BooleanField(default=False)),
                ('upload_date', models.DateTimeField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.documenttitle')),
            ],
            options={
                'db_table': 'document_clients',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('item_number', models.CharField(max_length=90)),
                ('make', models.CharField(max_length=90)),
                ('model', models.CharField(max_length=90)),
                ('serial_number', models.CharField(max_length=90)),
                ('equipment_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.equipmentgroup')),
            ],
            options={
                'db_table': 'equipment',
            },
        ),
        migrations.CreateModel(
            name='EquipmentUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.equipment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'equipment_user',
            },
        ),
        migrations.CreateModel(
            name='EquipmentTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calibrate_date', models.DateField(blank=True, null=True)),
                ('calibrate_freq', models.IntegerField(blank=True, null=True)),
                ('service_date', models.DateField(blank=True, null=True)),
                ('servcice_freq', models.IntegerField(blank=True, null=True)),
                ('inspection_date', models.DateField(blank=True, null=True)),
                ('inspection_freq', models.IntegerField(blank=True, null=True)),
                ('test_date', models.DateField(blank=True, null=True)),
                ('test_freq', models.IntegerField(blank=True, null=True)),
                ('equipmentuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.equipmentuser')),
            ],
            options={
                'db_table': 'equipment_test',
            },
        ),
        migrations.CreateModel(
            name='Qualifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification_name', models.CharField(max_length=90)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.rolenames')),
            ],
            options={
                'db_table': 'qualification',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=90)),
                ('last_name', models.CharField(max_length=90)),
                ('staff_id', models.CharField(max_length=45)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'staff',
            },
        ),
        migrations.CreateModel(
            name='StaffQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification_date', models.DateField(blank=True, null=True)),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.qualifications')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.staff')),
            ],
            options={
                'db_table': 'staff_qualification',
            },
        ),
        migrations.CreateModel(
            name='StaffRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.rolenames')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.staff')),
            ],
            options={
                'db_table': 'staff_role',
            },
        ),
    ]
