# Generated by Django 5.1.1 on 2024-10-27 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='equipmenttest',
            table='equipment_test',
        ),
    ]
